version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - jenkins-network

  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    ports:
      - "8090:8090"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - jenkins-network

networks:
  jenkins-network:
    external: true
